app.version=1.0.0
spring.application.nome=MongoDB
spring.data.mongodb.uri=mongodb://10.0.9.238:27017/dex
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
server.port=8080